// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'PlayerHand': string;
  'active': string;
  'cardContainer': string;
  'current': string;
  'description': string;
  'hand': string;
  'name': string;
  'out': string;
  'targetButton': string;
}
export const cssExports: CssExports;
export default cssExports;
