// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Play': string;
  'arrow': string;
  'arrows': string;
  'discard': string;
}
export const cssExports: CssExports;
export default cssExports;
