// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Opponents': string;
  'active': string;
  'cardWrapper': string;
  'current': string;
  'description': string;
  'hand': string;
  'name': string;
  'opponent': string;
  'out': string;
}
export const cssExports: CssExports;
export default cssExports;
