// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'GameStatus': string;
  'Overlay': string;
  'announcement': string;
  'gameOverMenu': string;
}
export const cssExports: CssExports;
export default cssExports;
