// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'SelectionWizard': string;
  'buttons': string;
  'guessDropdown': string;
  'message': string;
}
export const cssExports: CssExports;
export default cssExports;
