// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Board': string;
  'plays': string;
}
export const cssExports: CssExports;
export default cssExports;
