// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Card': string;
  'backDesign': string;
  'disabled': string;
  'empty': string;
  'faceUp': string;
  'properties': string;
  'selectable': string;
  'selected': string;
}
export const cssExports: CssExports;
export default cssExports;
